import type { NavigationItem } from "./types";

export const platformNavigation: NavigationItem[] = [
  {
    id: "platform-overview",
    label: "Visao Geral",
    path: "/platform/overview",
    scope: "platform",
    mode: "platform",
    requiredPermissions: ["platform:health:read"],
    allowedRoles: ["Super Admin"],
    status: "planned",
    icon: "platform-overview",
  },
  {
    id: "platform-tenants",
    label: "Tenants",
    path: "/platform/tenants",
    scope: "platform",
    mode: "platform",
    requiredPermissions: ["platform:tenants:read"],
    allowedRoles: ["Super Admin"],
    icon: "platform-tenants",
  },
  {
    id: "platform-modules",
    label: "Planos e Modulos",
    path: "/platform/plans-modules",
    scope: "platform",
    mode: "platform",
    requiredPermissions: ["platform:modules:manage"],
    allowedRoles: ["Super Admin"],
    status: "planned",
    icon: "platform-modules",
  },
  {
    id: "platform-cloud-billing",
    label: "Cloud Billing",
    path: "/platform/cloud-billing",
    scope: "platform",
    mode: "platform",
    requiredPermissions: [
      "platform:cloud-usage:read",
      "platform:cloud-costs:read",
      "platform:cloud-cost-allocation:read",
      "platform:cloud-charges:read",
      "platform:cloud-charge-rules:read",
    ],
    allowedRoles: ["Super Admin"],
    icon: "platform-cloud-billing",
  },
  {
    id: "platform-audit",
    label: "Auditoria Global",
    path: "/platform/audit",
    scope: "platform",
    mode: "platform",
    requiredPermissions: ["platform:audit:read"],
    allowedRoles: ["Super Admin"],
    status: "planned",
    icon: "platform-audit",
  },
  {
    id: "platform-health",
    label: "Health do Sistema",
    path: "/platform/health",
    scope: "platform",
    mode: "platform",
    requiredPermissions: ["platform:health:read"],
    allowedRoles: ["Super Admin"],
    status: "planned",
    icon: "platform-health",
  },
  {
    id: "platform-settings",
    label: "Configuracoes",
    path: "/platform/settings",
    scope: "platform",
    mode: "platform",
    requiredPermissions: ["platform:tenants:update"],
    allowedRoles: ["Super Admin"],
    status: "planned",
    icon: "platform-settings",
  },
];
