import type { NavigationItem } from "./types";

export const tenantNavigation: NavigationItem[] = [
  {
    id: "tenant-dashboard",
    label: "Dashboard",
    path: "/dashboard",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["dashboard:view"],
    icon: "dashboard",
    moduleKey: "dashboard",
  },
  {
    id: "tenant-work-orders",
    label: "Ordens de Servico",
    path: "/work-orders",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["work_orders:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "work-orders",
    moduleKey: "work-orders",
    status: "implemented",
  },
  {
    id: "tenant-logistics",
    label: "Painel Logistico",
    path: "/logistics",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["logistics:dispatch"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor"],
    icon: "logistics",
    moduleKey: "logistics",
  },
  {
    id: "tenant-checklist-runtime",
    label: "Checklists Operacionais",
    path: "/operations/checklists",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["checklist_runs:read", "checklist_runs:create"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "tenant_checklist",
    moduleKey: "tenant_checklist",
    featureKey: "checklist_runtime_web",
  },
  {
    id: "tenant-operations-map",
    label: "Mapa Operacional",
    path: "/operations/map",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["field_location:read"],
    icon: "Map",
    moduleKey: "field_operations",
    featureKey: "operations_map",
  },
  {
    id: "tenant-operations-dispatches",
    label: "Despachos",
    path: "/operations/dispatches",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["field_dispatch:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "Route",
    moduleKey: "field_operations",
    featureKey: "field_dispatch",
    status: "implemented",
  },
  {
    id: "tenant-registry-customers",
    label: "Clientes",
    path: "/cadastros/clientes",
    scope: "registry",
    mode: "operation",
    requiredPermissions: ["customers:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "Contact",
    status: "implemented",
  },
  {
    id: "tenant-registry-vehicles",
    label: "Viaturas",
    path: "/cadastros/viaturas",
    scope: "registry",
    mode: "operation",
    requiredPermissions: ["vehicles:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "Truck",
    status: "implemented",
  },
  {
    id: "tenant-registry-teams",
    label: "Equipes",
    path: "/cadastros/equipes",
    scope: "registry",
    mode: "operation",
    requiredPermissions: ["teams:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "UsersRound",
    status: "implemented",
  },
  {
    id: "tenant-registry-service-catalog",
    label: "Serviços",
    path: "/cadastros/servicos",
    scope: "registry",
    mode: "operation",
    requiredPermissions: ["service_catalog:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "Wrench",
    status: "implemented",
  },
  {
    id: "tenant-notifications",
    label: "Notificações",
    path: "/notifications",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["notifications:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico", "Auditor"],
    icon: "notifications",
    moduleKey: "notifications",
  },
  {
    id: "tenant-users",
    label: "Usuarios",
    path: "/users",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["users:read"],
    allowedRoles: ["Super Admin", "Administrador"],
    status: "planned",
    icon: "users",
    moduleKey: "users",
  },
  {
    id: "tenant-admin",
    label: "Administrador",
    path: "/administrator",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["tenant:manage", "roles:manage"],
    allowedRoles: ["Super Admin", "Administrador"],
    status: "planned",
    icon: "tenant-admin",
    moduleKey: "tenant-admin",
  },
  {
    id: "tenant-settings",
    label: "Configuracoes",
    path: "/administrator/settings",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["tenant:manage"],
    allowedRoles: ["Super Admin", "Administrador"],
    icon: "settings",
    moduleKey: "tenant-admin",
    featureKey: "tenant_settings",
  },
  {
    id: "tenant-checklists",
    label: "Checklists",
    path: "/administrator/checklists",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["tenant_checklists:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional"],
    icon: "tenant_checklist",
    moduleKey: "tenant_checklist",
    featureKey: "tenant_checklist",
  },
];
