import type { NavigationItem } from "./types";

export const tenantNavigation: NavigationItem[] = [
  {
    id: "tenant-dashboard",
    label: "Dashboard",
    path: "/dashboard",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["dashboard:view"],
    icon: "dashboard",
    moduleKey: "dashboard",
  },
  {
    id: "tenant-work-orders",
    label: "Ordens de Servico",
    path: "/work-orders",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["work-orders:view", "work-orders:create", "work-orders:update"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "work-orders",
    moduleKey: "work-orders",
  },
  {
    id: "tenant-logistics",
    label: "Painel Logistico",
    path: "/logistics",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["logistics:dispatch"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor"],
    icon: "logistics",
    moduleKey: "logistics",
  },
  {
    id: "tenant-checklist-runtime",
    label: "Checklists Operacionais",
    path: "/operations/checklists",
    scope: "tenant",
    mode: "operation",
    requiredPermissions: ["checklist_runs:read", "checklist_runs:create"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional", "Supervisor", "Operador Logistico"],
    icon: "tenant_checklist",
    moduleKey: "tenant_checklist",
    featureKey: "checklist_runtime_web",
  },
  {
    id: "tenant-users",
    label: "Usuarios",
    path: "/users",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["users:read"],
    allowedRoles: ["Super Admin", "Administrador"],
    status: "planned",
    icon: "users",
    moduleKey: "users",
  },
  {
    id: "tenant-admin",
    label: "Administrador",
    path: "/administrator",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["tenant:manage", "roles:manage"],
    allowedRoles: ["Super Admin", "Administrador"],
    status: "planned",
    icon: "tenant-admin",
    moduleKey: "tenant-admin",
  },
  {
    id: "tenant-settings",
    label: "Configuracoes",
    path: "/administrator/settings",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["tenant:manage"],
    allowedRoles: ["Super Admin", "Administrador"],
    icon: "settings",
    moduleKey: "tenant-admin",
    featureKey: "tenant_settings",
  },
  {
    id: "tenant-checklists",
    label: "Checklists",
    path: "/administrator/checklists",
    scope: "tenant",
    mode: "tenant_admin",
    requiredPermissions: ["tenant_checklists:read"],
    allowedRoles: ["Super Admin", "Administrador", "Gestor Operacional"],
    icon: "tenant_checklist",
    moduleKey: "tenant_checklist",
    featureKey: "tenant_checklist",
  },
];
