import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { buildSnapshot,verifyAttestation,checkAllowlist } from '../scripts/porteiro-pre-merge.mjs';
import { assertMergeCandidate } from '../scripts/merge-authorized-pr.mjs';

const H='a'.repeat(40),B='b'.repeat(40);
const state=()=>({repo:'acme/erp',pr:{number:9,state:'open',draft:false,body:'escopo',head:{ref:'feat/x',sha:H},base:{ref:'main',sha:B}},rulesets:[{id:1,enforcement:'active',bypass_actors:[],rules:[{type:'required_status_checks',parameters:{strict_required_status_checks_policy:true,required_status_checks:[{context:'ci',integration_id:10},{context:'erp/porteiro-pre-merge',integration_id:20}]}}]}],checks:[{context:'ci',appId:10,conclusion:'success',detailsUrl:'https://ci'}],junta:{marker:'erp-junta-attestation:v1',result:'APROVADO',origin:'owner',planner:'planner',developer:'dev',votes:[{agentId:'r1',vote:'APROVADO'},{agentId:'r2',vote:'APROVADO'},{agentId:'r3',vote:'APROVADO'}]},juntaBlobOid:'c'.repeat(40)});
const att=(s:any)=>({schema:'erp-porteiro-attestation:v1',verdict:`LIBERADO: merge do PR #9 no head ${H}`,repo:'acme/erp',pr:9,head:H,snapshotSha256:s.snapshotSha256,agentId:'porter',role:'porteiro-pos-merge',runtime:'codex',model:'gpt-5.6-sol',reasoningEffort:'ultra',independentOf:['owner','planner','dev','r1','r2','r3'],commands:['npm test']});

test('snapshot canônico liga repo/PR/head/base/body/check/ruleset/junta e aceita recibo exato',()=>{const s=buildSnapshot(state());assert.equal(s.bodySha256.length,64);assert.equal(s.ruleset.sha256.length,64);assert.equal(verifyAttestation(s,att(s)),true);});
test('mutações discriminantes alteram snapshot ou fecham o gate',()=>{const original=buildSnapshot(state());for(const mutate of [(x:any)=>x.pr.head.sha='d'.repeat(40),(x:any)=>x.pr.base.sha='e'.repeat(40),(x:any)=>x.pr.body='mudou',(x:any)=>x.checks[0].detailsUrl='https://ci/new',(x:any)=>x.rulesets[0].id=2]){const x=state();mutate(x);assert.notEqual(buildSnapshot(x).snapshotSha256,original.snapshotSha256);}const badCheck=state();badCheck.checks[0].conclusion='failure';assert.throws(()=>buildSnapshot(badCheck),/não verde/);const bypass=state();bypass.rulesets[0].bypass_actors=[{actor_id:1}];assert.throws(()=>buildSnapshot(bypass),/bypass/);const dup=state();dup.junta.votes[0].agentId='dev';assert.throws(()=>buildSnapshot(dup),/repetida/);});
test('ressalva, comentário ausente conceitual, SHA curto e receipt degradado não liberam',()=>{const s=buildSnapshot(state());for(const patch of [{verdict:`LIBERADO COM RESSALVA: PR #9 head ${H}`},{head:H.slice(0,12)},{reasoningEffort:'high'},{model:'gpt-5.6-terra'},{agentId:'dev'}])assert.throws(()=>verifyAttestation(s,{...att(s),...patch}));});
test('merge CAS exige snapshot/status/permalink/head e executor independentes',()=>{const s=buildSnapshot(state()),a=att(s),c={html_url:'https://gh/comment/1'},status={context:'erp/porteiro-pre-merge',state:'success',target_url:c.html_url};assert.equal(assertMergeCandidate({snapshot:s,currentSnapshot:s,attestation:a,status,comment:c,expectedHead:H,mergeAgentId:'merger'}),true);assert.throws(()=>assertMergeCandidate({snapshot:s,currentSnapshot:s,attestation:a,status,comment:c,expectedHead:'f'.repeat(40),mergeAgentId:'merger'}),/head divergiu/);assert.throws(()=>assertMergeCandidate({snapshot:s,currentSnapshot:s,attestation:a,status:{...status,target_url:'x'},comment:c,expectedHead:H,mergeAgentId:'merger'}),/permalink/);});
test('workflow nunca executa código do head em pull_request_target e ruleset é strict sem bypass',()=>{const y=readFileSync('.github/workflows/porteiro-pre-merge.yml','utf8');assert.match(y,/pull_request_target:/);assert.doesNotMatch(y,/ref:\s*\$\{\{\s*github\.event\.pull_request\.head/);assert.match(y,/ref: main/);const r=JSON.parse(readFileSync('.github/rulesets/main.template.json','utf8'));assert.deepEqual(r.bypass_actors,[]);assert.equal(r.enforcement,'active');assert.equal(r.rules.find((x:any)=>x.type==='required_status_checks').parameters.strict_required_status_checks_policy,true);});
test('guard de allowlist falha para qualquer path não manifestado',()=>{assert.equal(checkAllowlist(['CLAUDE.md'],new Set(['CLAUDE.md'])),true);assert.throws(()=>checkAllowlist(['CLAUDE.md','src/escape.ts'],new Set(['CLAUDE.md'])),/src\/escape/);});
