import { loadRegistry, loadMvp, flatten } from "./load.mjs";
const S = process.argv[2];
const reg = flatten(loadRegistry(`${S}/registry.ts`));
const mvp = loadMvp(`${S}/appSidebarNav.ts`);
const regPaths = new Set(reg.map((e) => e.path));
const mvpSet = new Set(mvp);
console.log("entradas do registro (recursivo):", reg.length, "| caminhos distintos:", regPaths.size, "| filhos (depth>0):", reg.filter(e=>e.depth>0).length);
console.log("MVP_NAV_PATHS:", mvp.length, "distintos:", mvpSet.size);
const mvpMinusReg = [...mvpSet].filter((p) => !regPaths.has(p)).sort();
console.log("MVP - registro =", mvpMinusReg.length);
const semMod = reg.filter((e) => !e.requiredModules?.length);
console.log("registro SEM requiredModules =", semMod.length);
for (const e of semMod) console.log("   ", e.platformOnly ? "[platformOnly]" : e.tenantOnly ? "[tenantOnly]" : "[--]", e.path, "| MVP:", mvpSet.has(e.path) ? "sim" : "nao", "| group:", e.group);
const semModTenantMvp = semMod.filter((e) => !e.platformOnly && mvpSet.has(e.path));
console.log("registro SEM modulo, nao-platformOnly, no MVP =", semModTenantMvp.length);
const pt = semMod.filter((e) => /^\/(patios|telemetria)\//.test(e.path));
console.log("  dos quais /patios/* e /telemetria/* =", pt.length, pt.map(e=>e.path).join(" "));
console.log("27 + 11 disjuntos?", mvpMinusReg.filter((p)=>pt.some(e=>e.path===p)).length === 0);
console.log("MVP - registro:", mvpMinusReg.join(" "));
const comMod = reg.filter((e) => e.requiredModules?.length);
console.log("registro COM requiredModules =", comMod.length, "chaves usadas:", [...new Set(comMod.flatMap(e=>e.requiredModules))].join(","));
