import type { NavigationItem } from "./navigation.types.js";

export const NAVIGATION_REGISTRY: readonly NavigationItem[] = [
  {
    id: "platform.dashboard",
    label: "Visão Geral",
    description: "Resumo executivo do Console da Plataforma.",
    path: "/platform/dashboard",
    icon: "LayoutDashboard",
    group: "platform",
    order: 10,
    status: "planned",
    requiredPermissions: ["platform:dashboard:read"],
    platformOnly: true,
  },
  {
    id: "platform.tenants",
    label: "Tenants",
    description: "Gestao global de tenants, planos e status.",
    path: "/platform/tenants",
    icon: "Building2",
    group: "platform",
    order: 20,
    status: "implemented",
    requiredPermissions: ["platform:tenants:read"],
    platformOnly: true,
    relatedEndpoints: [
      "GET /api/v1/platform/tenants",
      "POST /api/v1/platform/tenants",
      "PATCH /api/v1/platform/tenants/:tenantId/status",
    ],
  },
  {
    id: "platform.cloudBilling",
    label: "Billing Cloud",
    description: "Uso, custo, rateio, cobrança e margem cloud no boundary Platform.",
    path: "/platform/cloud-billing",
    icon: "Receipt",
    group: "platform",
    order: 30,
    status: "implemented",
    requiredPermissions: ["platform:cloud-charges:read"],
    platformOnly: true,
    relatedEndpoints: [
      "GET /api/v1/platform/cloud-usage/summary",
      "GET /api/v1/platform/cloud-costs/summary",
      "GET /api/v1/platform/cloud-cost-allocations/summary",
      "GET /api/v1/platform/cloud-charges/summary",
    ],
  },
  {
    id: "platform.audit",
    label: "Auditoria Platform",
    description: "Auditoria global e eventos sensiveis da plataforma.",
    path: "/platform/audit",
    icon: "ShieldCheck",
    group: "platform",
    order: 40,
    status: "planned",
    requiredPermissions: ["platform:audit:read"],
    platformOnly: true,
  },
  {
    id: "tenant.dashboard",
    label: "Dashboard",
    description: "Indicadores operacionais do tenant ativo.",
    path: "/dashboard",
    icon: "LayoutDashboard",
    group: "tenant",
    order: 100,
    status: "partial",
    requiredPermissions: ["dashboard:read"],
    requiredModules: ["dashboard"],
    tenantOnly: true,
  },
  {
    id: "tenant.checklists",
    label: "Checklists",
    description: "Configuracao de checklists do tenant.",
    path: "/administrator/checklists",
    icon: "ClipboardCheck",
    group: "tenant",
    order: 110,
    status: "implemented",
    requiredPermissions: ["tenant_checklists:read"],
    requiredModules: ["tenant_checklist", "checklists"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/tenant/checklists",
      "POST /api/v1/tenant/checklists",
      "GET /api/v1/tenant/checklists/templates",
      "GET /api/v1/tenant/checklist-components",
    ],
  },
  {
    id: "tenant.settings",
    label: "Configurações",
    description: "Configuracoes administrativas do tenant.",
    path: "/administrator/settings",
    icon: "Settings",
    group: "tenant",
    order: 120,
    status: "partial",
    requiredPermissions: ["tenant_settings:read"],
    requiredModules: ["tenant-admin"],
    tenantOnly: true,
  },
  {
    id: "tenant.users",
    label: "Usuários",
    description: "Usuarios e acessos do tenant.",
    path: "/administrator/users",
    icon: "UsersRound",
    group: "tenant",
    order: 130,
    status: "planned",
    requiredPermissions: ["users:read"],
    requiredModules: ["users"],
    tenantOnly: true,
  },
  {
    id: "tenant.audit",
    label: "Auditoria",
    description: "Eventos auditaveis do tenant.",
    path: "/administrator/audit",
    icon: "ScrollText",
    group: "tenant",
    order: 140,
    status: "backend-ready",
    requiredPermissions: ["audit:read"],
    requiredModules: ["audit"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/audit-events"],
  },
  {
    id: "tenant.notifications",
    label: "Notificações",
    description: "Inbox interna do usuario autenticado.",
    path: "/notifications",
    icon: "Bell",
    group: "tenant",
    order: 150,
    status: "implemented",
    requiredPermissions: ["notifications:read"],
    requiredModules: ["notifications"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/notifications",
      "GET /api/v1/notifications/unread-count",
    ],
  },
  {
    id: "operations.checklists",
    label: "Checklists Operacionais",
    description: "Execucao de checklists publicados.",
    path: "/operations/checklists",
    icon: "ClipboardList",
    group: "operations",
    order: 200,
    status: "implemented",
    requiredPermissions: ["checklist_runs:read"],
    requiredModules: ["tenant_checklist", "checklists"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/mobile/checklists/available"],
  },
  {
    id: "operations.checklistRun",
    label: "Executar Checklist",
    description: "Runtime de checklist orientado por schema.",
    path: "/operations/checklists/:checklistId/run",
    icon: "PlayCircle",
    group: "operations",
    order: 210,
    status: "implemented",
    requiredPermissions: ["checklist_runs:create"],
    requiredModules: ["tenant_checklist", "checklists"],
    tenantOnly: true,
  },
  {
    id: "operations.workOrders",
    label: "Ordens de Serviço",
    description: "Lista e fluxo de ordens de servico.",
    path: "/work-orders",
    icon: "Wrench",
    group: "operations",
    order: 220,
    status: "implemented",
    requiredPermissions: ["work_orders:read"],
    requiredModules: ["work_orders", "work-orders"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/work-orders",
      "POST /api/v1/work-orders",
      "GET /api/v1/work-orders/:workOrderId",
      "PATCH /api/v1/work-orders/:workOrderId",
      "PATCH /api/v1/work-orders/:workOrderId/status",
      "POST /api/v1/work-orders/:workOrderId/assign",
      "GET /api/v1/work-orders/:workOrderId/timeline",
    ],
  },
  {
    id: "operations.map",
    label: "Mapa Operacional",
    description: "Mapa operacional planejado para equipes em campo.",
    path: "/operations/map",
    icon: "Map",
    group: "operations",
    order: 230,
    status: "backend-ready",
    requiredPermissions: ["field_location:read"],
    requiredModules: ["field_operations"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/field-locations/latest",
      "GET /api/v1/field-locations/history",
    ],
  },
  {
    id: "operations.fieldOperators",
    label: "Operadores em Campo",
    description: "Visao planejada de operadores e localizacao.",
    path: "/operations/field-operators",
    icon: "MapPin",
    group: "operations",
    order: 240,
    status: "planned",
    requiredPermissions: ["field_operator:read"],
    requiredModules: ["field_operations"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/field-locations/latest"],
  },
  {
    id: "operations.dispatches",
    label: "Despachos",
    description: "Despacho operacional e acompanhamento de rotas.",
    path: "/operations/dispatches",
    icon: "Route",
    group: "operations",
    order: 250,
    status: "planned",
    requiredPermissions: ["field_dispatch:read"],
    requiredModules: ["field_operations"],
    tenantOnly: true,
  },
  {
    id: "logistics.dashboard",
    label: "Logística",
    description: "Painel logistico do tenant.",
    path: "/logistics",
    icon: "Truck",
    group: "logistics",
    order: 300,
    status: "planned",
    requiredPermissions: ["logistics:read"],
    requiredModules: ["logistics"],
    tenantOnly: true,
  },
  {
    id: "logistics.routes",
    label: "Rotas",
    description: "Rotas logisticas planejadas.",
    path: "/logistics/routes",
    icon: "Route",
    group: "logistics",
    order: 310,
    status: "planned",
    requiredPermissions: ["logistics_routes:read"],
    requiredModules: ["logistics"],
    tenantOnly: true,
  },
  {
    id: "logistics.map",
    label: "Mapa Logístico",
    description: "Mapa logistico planejado.",
    path: "/logistics/map",
    icon: "MapPinned",
    group: "logistics",
    order: 320,
    status: "planned",
    requiredPermissions: ["field_location:read"],
    requiredModules: ["logistics", "field_operations"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/field-locations/latest",
      "GET /api/v1/field-locations/history",
    ],
  },
  {
    id: "finance.dashboard",
    label: "Financeiro",
    description: "Visao financeira planejada.",
    path: "/finance",
    icon: "ChartNoAxesCombined",
    group: "finance",
    order: 400,
    status: "future",
    requiredPermissions: ["finance:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  {
    id: "finance.charges",
    label: "Cobranças",
    description: "Cobrancas planejadas do tenant.",
    path: "/finance/charges",
    icon: "ReceiptText",
    group: "finance",
    order: 410,
    status: "future",
    requiredPermissions: ["billing:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  {
    id: "finance.invoices",
    label: "Faturas",
    description: "Faturas planejadas do tenant.",
    path: "/finance/invoices",
    icon: "FileText",
    group: "finance",
    order: 420,
    status: "future",
    requiredPermissions: ["invoices:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  {
    id: "finance.payments",
    label: "Pagamentos",
    description: "Pagamentos planejados do tenant.",
    path: "/finance/payments",
    icon: "CreditCard",
    group: "finance",
    order: 430,
    status: "future",
    requiredPermissions: ["payments:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
];
