import type { NavigationItem } from "./navigation.types.js";

export const NAVIGATION_REGISTRY: readonly NavigationItem[] = [
  {
    id: "platform.dashboard",
    label: "Visão Geral",
    description: "Resumo executivo do Console da Plataforma.",
    path: "/platform/dashboard",
    icon: "LayoutDashboard",
    group: "platform",
    order: 10,
    status: "planned",
    requiredPermissions: ["platform:dashboard:read"],
    platformOnly: true,
  },
  {
    id: "platform.tenants",
    label: "Tenants",
    description: "Gestao global de tenants, planos e status.",
    path: "/platform/tenants",
    icon: "Building2",
    group: "platform",
    order: 20,
    status: "implemented",
    requiredPermissions: ["platform:tenants:read"],
    platformOnly: true,
    relatedEndpoints: [
      "GET /api/v1/platform/tenants",
      "POST /api/v1/platform/tenants",
      "PATCH /api/v1/platform/tenants/:tenantId/status",
    ],
  },
  {
    id: "platform.cloudBilling",
    label: "Billing Cloud",
    description: "Uso, custo, rateio, cobrança e margem cloud no boundary Platform.",
    path: "/platform/cloud-billing",
    icon: "Receipt",
    group: "platform",
    order: 30,
    status: "implemented",
    requiredPermissions: ["platform:cloud-charges:read"],
    platformOnly: true,
    relatedEndpoints: [
      "GET /api/v1/platform/cloud-usage/summary",
      "GET /api/v1/platform/cloud-costs/summary",
      "GET /api/v1/platform/cloud-cost-allocations/summary",
      "GET /api/v1/platform/cloud-charges/summary",
    ],
  },
  {
    id: "platform.audit",
    label: "Auditoria Platform",
    description: "Auditoria global e eventos sensiveis da plataforma.",
    path: "/platform/audit",
    icon: "ShieldCheck",
    group: "platform",
    order: 40,
    status: "planned",
    requiredPermissions: ["platform:audit:read"],
    platformOnly: true,
  },
  {
    id: "tenant.dashboard",
    label: "Dashboard",
    description: "Indicadores operacionais do tenant ativo.",
    path: "/dashboard",
    icon: "LayoutDashboard",
    group: "tenant",
    order: 100,
    status: "partial",
    requiredPermissions: ["dashboard:read"],
    requiredModules: ["dashboard"],
    tenantOnly: true,
  },
  {
    id: "tenant.checklists",
    label: "Checklists",
    description: "Configuracao de checklists do tenant.",
    path: "/administrator/checklists",
    icon: "ClipboardCheck",
    group: "tenant",
    order: 110,
    status: "implemented",
    requiredPermissions: ["tenant_checklists:read"],
    requiredModules: ["tenant_checklist", "checklists"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/tenant/checklists",
      "POST /api/v1/tenant/checklists",
      "GET /api/v1/tenant/checklists/templates",
      "GET /api/v1/tenant/checklist-components",
    ],
  },
  {
    id: "tenant.settings",
    label: "Configurações",
    description: "Configuracoes administrativas do tenant.",
    path: "/administrator/settings",
    icon: "Settings",
    group: "tenant",
    order: 120,
    status: "partial",
    requiredPermissions: ["tenant_settings:read"],
    requiredModules: ["tenant-admin"],
    tenantOnly: true,
  },
  {
    id: "tenant.users",
    label: "Usuários",
    description: "Usuarios e acessos do tenant.",
    path: "/administrator/users",
    icon: "UsersRound",
    group: "tenant",
    order: 130,
    status: "planned",
    requiredPermissions: ["users:read"],
    requiredModules: ["users"],
    tenantOnly: true,
  },
  {
    id: "tenant.audit",
    label: "Auditoria",
    description: "Eventos auditaveis do tenant.",
    path: "/administrator/audit",
    icon: "ScrollText",
    group: "tenant",
    order: 140,
    status: "backend-ready",
    requiredPermissions: ["audit:read"],
    requiredModules: ["audit"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/audit-events"],
  },
  {
    id: "tenant.notifications",
    label: "Notificações",
    description: "Inbox interna do usuario autenticado.",
    path: "/notifications",
    icon: "Bell",
    group: "tenant",
    order: 150,
    status: "implemented",
    requiredPermissions: ["notifications:read"],
    requiredModules: ["notifications"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/notifications",
      "GET /api/v1/notifications/unread-count",
    ],
  },
  {
    // Ω4C PR-20 — Central de Notificações (tenant-wide): path GOVERNADO (esconde-fino, lição do PR-14). Gate
    // ÚNICO `notifications:create` (gestão/broadcast; SEM permissão nova) e SEM requiredModules — sem provisão
    // de módulo novo; getGovernedNavigationPaths o inclui, então o gating dinâmico ESCONDE o item de quem NÃO
    // tem notifications:create (ex.: field_technician/finance/auditor), que segue barrado no 403 do backend.
    // Distinto de tenant.notifications (inbox/sino, notifications:read amplo).
    id: "tenant.notificationsCentral",
    label: "Central de Notificações",
    description: "Gestão tenant-wide das notificações agendadas da organização (qualquer criador).",
    path: "/controle/notificacoes",
    icon: "BellRing",
    group: "tenant",
    order: 155,
    status: "implemented",
    requiredPermissions: ["notifications:create"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/notifications/scheduled/central",
      "DELETE /api/v1/notifications/scheduled/central/:scheduledNotificationId",
      "POST /api/v1/notifications/scheduled",
    ],
  },
  {
    id: "operations.checklists",
    label: "Checklists Operacionais",
    description: "Execucao de checklists publicados.",
    path: "/operations/checklists",
    icon: "ClipboardList",
    group: "operations",
    order: 200,
    status: "implemented",
    requiredPermissions: ["checklist_runs:read"],
    requiredModules: ["tenant_checklist", "checklists"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/mobile/checklists/available"],
  },
  {
    id: "operations.checklistRun",
    label: "Executar Checklist",
    description: "Runtime de checklist orientado por schema.",
    path: "/operations/checklists/:checklistId/run",
    icon: "PlayCircle",
    group: "operations",
    order: 210,
    status: "implemented",
    requiredPermissions: ["checklist_runs:create"],
    requiredModules: ["tenant_checklist", "checklists"],
    tenantOnly: true,
  },
  {
    id: "operations.workOrders",
    label: "Ordens de Serviço",
    description: "Lista e fluxo de ordens de servico.",
    path: "/work-orders",
    icon: "Wrench",
    group: "operations",
    order: 220,
    status: "implemented",
    requiredPermissions: ["work_orders:read"],
    requiredModules: ["work_orders", "work-orders"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/work-orders",
      "POST /api/v1/work-orders",
      "GET /api/v1/work-orders/:workOrderId",
      "PATCH /api/v1/work-orders/:workOrderId",
      "PATCH /api/v1/work-orders/:workOrderId/status",
      "POST /api/v1/work-orders/:workOrderId/assign",
      "GET /api/v1/work-orders/:workOrderId/timeline",
    ],
  },
  {
    id: "operations.map",
    label: "Mapa Operacional",
    description: "Mapa operacional de equipes em campo com vinculo opcional a OS.",
    path: "/operations/map",
    icon: "Map",
    group: "operations",
    order: 230,
    status: "implemented",
    requiredPermissions: ["field_location:read"],
    requiredModules: ["field_operations"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/field-locations/latest",
      "GET /api/v1/field-locations/history",
      "GET /api/v1/work-orders",
      "GET /api/v1/work-orders/:workOrderId",
      "GET /api/v1/operations/dispatches",
      "PATCH /api/v1/operations/dispatches/:dispatchId/status",
      "PATCH /api/v1/operations/dispatches/:dispatchId/reassign",
    ],
  },
  {
    id: "operations.fieldOperators",
    label: "Operadores em Campo",
    description: "Visao planejada de operadores e localizacao.",
    path: "/operations/field-operators",
    icon: "MapPin",
    group: "operations",
    order: 240,
    status: "planned",
    requiredPermissions: ["field_operator:read"],
    requiredModules: ["field_operations"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/field-locations/latest"],
  },
  {
    // Ω3-a — Orçamentos: path GOVERNADO (veto coordenador-de-acessos V1). Só permissão (sem
    // requiredModules) — sem provisão de módulo novo; getGovernedNavigationPaths o inclui, então o
    // gating dinâmico ESCONDE o item de quem não tem service_quotes:read (ex.: inventory).
    id: "operations.quotes",
    label: "Orçamentos",
    description: "Orçamentos com preço congelado a partir da Tarifa vigente.",
    path: "/operations/quotes",
    icon: "Calculator",
    group: "operations",
    order: 245,
    status: "implemented",
    requiredPermissions: ["service_quotes:read"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/service-quotes",
      "POST /api/v1/service-quotes",
      "GET /api/v1/service-quotes/:serviceQuoteId",
      "PATCH /api/v1/service-quotes/:serviceQuoteId",
      "PATCH /api/v1/service-quotes/:serviceQuoteId/status",
    ],
  },
  {
    id: "operations.dispatches",
    label: "Despachos",
    description: "Despacho operacional vinculado a OS, operador e mapa.",
    path: "/operations/dispatches",
    icon: "Route",
    group: "operations",
    order: 250,
    status: "implemented",
    requiredPermissions: ["field_dispatch:read"],
    requiredModules: ["field_operations"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/operations/dispatches",
      "POST /api/v1/operations/dispatches",
      "GET /api/v1/operations/dispatches/:dispatchId",
      "PATCH /api/v1/operations/dispatches/:dispatchId/status",
      "PATCH /api/v1/operations/dispatches/:dispatchId/reassign",
    ],
  },
  {
    id: "logistics.dashboard",
    label: "Logística",
    description: "Painel logistico do tenant.",
    path: "/logistics",
    icon: "Truck",
    group: "logistics",
    order: 300,
    status: "planned",
    requiredPermissions: ["logistics:read"],
    requiredModules: ["logistics"],
    tenantOnly: true,
  },
  {
    id: "logistics.routes",
    label: "Rotas",
    description: "Rotas logisticas planejadas.",
    path: "/logistics/routes",
    icon: "Route",
    group: "logistics",
    order: 310,
    status: "planned",
    requiredPermissions: ["logistics_routes:read"],
    requiredModules: ["logistics"],
    tenantOnly: true,
  },
  {
    id: "logistics.map",
    label: "Mapa Logístico",
    description: "Mapa logistico planejado.",
    path: "/logistics/map",
    icon: "MapPinned",
    group: "logistics",
    order: 320,
    status: "planned",
    requiredPermissions: ["field_location:read"],
    requiredModules: ["logistics", "field_operations"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/field-locations/latest",
      "GET /api/v1/field-locations/history",
    ],
  },
  {
    id: "finance.dashboard",
    label: "Financeiro",
    description: "Visao financeira planejada.",
    path: "/finance",
    icon: "ChartNoAxesCombined",
    group: "finance",
    order: 400,
    status: "future",
    requiredPermissions: ["finance:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  {
    id: "finance.charges",
    label: "Cobranças",
    description: "Cobrancas planejadas do tenant.",
    path: "/finance/charges",
    icon: "ReceiptText",
    group: "finance",
    order: 410,
    status: "future",
    requiredPermissions: ["billing:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  {
    id: "finance.invoices",
    label: "Faturas",
    description: "Faturas planejadas do tenant.",
    path: "/finance/invoices",
    icon: "FileText",
    group: "finance",
    order: 420,
    status: "future",
    requiredPermissions: ["invoices:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  {
    id: "finance.payments",
    label: "Pagamentos",
    description: "Pagamentos planejados do tenant.",
    path: "/finance/payments",
    icon: "CreditCard",
    group: "finance",
    order: 430,
    status: "future",
    requiredPermissions: ["payments:read"],
    requiredModules: ["finance"],
    tenantOnly: true,
  },
  // Ω4C PR-14 — Telemetria (app de campo): 4 paths GOVERNADOS (veto coordenador-de-acessos, mesma classe
  // do V1 de Orçamentos). Gate ÚNICO `telemetry:read` (PR-12; SEM permissão nova) e SEM requiredModules —
  // sem provisão de módulo novo; getGovernedNavigationPaths os inclui, então o gating dinâmico ESCONDE o
  // grupo TELEMETRIA de quem não tem telemetry:read (ex.: field_technician), que segue barrado no 403 do
  // backend. O Rastreamento/mapa fica FORA (PR-15, Junta de Mapas).
  {
    id: "telemetry.quilometragem",
    label: "Quilometragem",
    description: "Quilometragem por operador/viatura a partir da telemetria do app de campo.",
    path: "/telemetria/quilometragem",
    icon: "Gauge",
    group: "tenant",
    order: 160,
    status: "implemented",
    requiredPermissions: ["telemetry:read"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/telemetry/km"],
  },
  {
    id: "telemetry.acessos",
    label: "Acessos",
    description: "Conexões/desconexões do app de campo (telemetria).",
    path: "/telemetria/acessos",
    icon: "Smartphone",
    group: "tenant",
    order: 170,
    status: "implemented",
    requiredPermissions: ["telemetry:read"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/telemetry/access"],
  },
  {
    id: "telemetry.recusas",
    label: "Recusas",
    description: "Recusas de despacho registradas pela telemetria do app de campo.",
    path: "/telemetria/recusas",
    icon: "Ban",
    group: "tenant",
    order: 180,
    status: "implemented",
    requiredPermissions: ["telemetry:read"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/telemetry/refusals"],
  },
  {
    id: "telemetry.dispositivos",
    label: "Dispositivos",
    description: "Dispositivos do app de campo vistos pela telemetria.",
    path: "/telemetria/dispositivos",
    icon: "Tablet",
    group: "tenant",
    order: 190,
    status: "implemented",
    requiredPermissions: ["telemetry:read"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/telemetry/devices"],
  },
  {
    // Ω4C PR-15 (Junta de Mapas J-MAPAS-9) — Rastreamento (mapa do trajeto): path GOVERNADO (lição de
    // esconde-fino do PR-14). Gate ÚNICO telemetry:read (SEM permissão nova) e SEM requiredModules — sem
    // provisão de módulo novo; getGovernedNavigationPaths o inclui (28→29), então o gating dinâmico ESCONDE o
    // item de quem não tem telemetry:read (ex.: field_technician), que segue barrado no 403 do backend. É a
    // ÚNICA superfície que consome /telemetry/track (coordenada crua, gated forte + consent na origem).
    id: "telemetry.rastreamento",
    label: "Rastreamento",
    description: "Trajeto (mapa) do profissional a partir da telemetria consentida do app de campo.",
    path: "/telemetria/rastreamento",
    icon: "Route",
    group: "tenant",
    order: 195,
    status: "implemented",
    requiredPermissions: ["telemetry:read"],
    tenantOnly: true,
    relatedEndpoints: ["GET /api/v1/telemetry/track"],
  },
  // Ω5P PR-04 — Pátios (console do operador): 3 paths GOVERNADOS (esconde-fino, lição Ω4C PR-14/15/20). Cada um
  // com gate ÚNICO por permissão (yard:read / jurisdiction:read / price_tables:read; SEM permissão nova) e SEM
  // requiredModules — sem provisão de módulo novo (igual a operations.quotes/telemetria/central). Assim
  // getGovernedNavigationPaths os inclui e o gating dinâmico OCULTA de quem não tem a permissão (finance/inventory/
  // support), que segue barrado no 403 do backend. O drilldown /patios/patios/:yardId NÃO é item de sidebar (não é
  // governed; gate pelo route-guard). Nenhuma migração — dado, não DDL.
  {
    id: "patios.yards",
    label: "Pátios",
    description: "Cadastro físico dos pátios de recolhimento: áreas hierárquicas e vagas.",
    path: "/patios/patios",
    icon: "Warehouse",
    group: "tenant",
    order: 260,
    status: "implemented",
    requiredPermissions: ["yard:read"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/yards",
      "POST /api/v1/yards",
      "GET /api/v1/yards/:yardId",
      "PATCH /api/v1/yards/:yardId",
      "GET /api/v1/yards/:yardId/occupancy",
      "GET /api/v1/yards/:yardId/areas",
      "POST /api/v1/yards/:yardId/areas",
      "PATCH /api/v1/yard-areas/:areaId",
      "GET /api/v1/yard-areas/:areaId/spots",
      "POST /api/v1/yard-areas/:areaId/spots",
      "PATCH /api/v1/yard-spots/:spotId",
    ],
  },
  {
    id: "patios.profiles",
    label: "Perfis Normativos",
    description: "Parametrização nacional por convênio público / contrato privado: prazos, diária, teto e exigências.",
    path: "/patios/perfis",
    icon: "Scale",
    group: "tenant",
    order: 270,
    status: "implemented",
    requiredPermissions: ["jurisdiction:read"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/jurisdiction-profiles",
      "POST /api/v1/jurisdiction-profiles",
      "GET /api/v1/jurisdiction-profiles/:profileId",
      "PATCH /api/v1/jurisdiction-profiles/:profileId",
      "GET /api/v1/jurisdiction-defaults",
    ],
  },
  {
    id: "patios.tariffs",
    label: "Tabela de Valores",
    description: "Tabelas de valores por escopo (público/privado) e categoria de veículo para o pátio.",
    path: "/patios/tarifas",
    icon: "Coins",
    group: "tenant",
    order: 280,
    status: "implemented",
    requiredPermissions: ["price_tables:read"],
    tenantOnly: true,
    relatedEndpoints: [
      "GET /api/v1/price-tables",
      "POST /api/v1/price-tables",
      "GET /api/v1/price-tables/:priceTableId",
      "PATCH /api/v1/price-tables/:priceTableId",
    ],
  },
];
