#!/usr/bin/env node
import { readFileSync,writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const ROOT=fileURLToPath(new URL('../',import.meta.url));const latestPath=`${ROOT}Kpis/kpis-latest.json`;const histPath=`${ROOT}Kpis/kpis-history.json`;const mdPath=`${ROOT}Kpis/kpis-history.md`;
const arg=(n)=>{const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:undefined;};const fail=(m)=>{throw new Error(m);};const read=(p)=>JSON.parse(readFileSync(p,'utf8'));const write=(p,v)=>writeFileSync(p,`${JSON.stringify(v,null,2)}\n`);
const gh=(a)=>JSON.parse(execFileSync('gh',a,{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']}));
export function authorRelease(latest,history,input){
  if(input.pr!==null||input.merge_commit!==null||input.approved_head!==null)fail('autoria exige pr/merge_commit/approved_head null');
  for(const k of ['snapshot_date','version','block','title','summary','backend_tests','frontend_smoke_tests','flutter_tests','blocks_completed'])if(input[k]===undefined)fail(`campo obrigatório: ${k}`);
  const metric=(display,note)=>{const [value,total=value]=String(display).split('/').map(Number);if(!Number.isFinite(value)||!Number.isFinite(total))fail(`métrica inválida: ${display}`);return {value,total,display:String(display),note};};
  const next=structuredClone(latest);Object.assign(next,{snapshot_date:input.snapshot_date,version:input.version});next.release={block:input.block,title:input.title,pr:null,merge_commit:null,approved_head:null,status:'published_per_pr',summary:input.summary};next.metrics={...next.metrics,backend_tests:metric(input.backend_tests,input.backend_note||input.summary),frontend_smoke_tests:metric(input.frontend_smoke_tests,input.frontend_note||'CARREGADO: trilha frontend não tocada.'),flutter_tests:metric(input.flutter_tests,input.flutter_note||'CARREGADO: trilha Flutter não tocada.'),blocks_completed:{value:Number(input.blocks_completed),display:String(input.blocks_completed),note:input.blocks_note||'Inalterado: governança não move escopo de produto.'}};
  const row={snapshot_date:input.snapshot_date,version:input.version,pr:null,merge_commit:null,approved_head:null,backend_tests:input.backend_tests,frontend_smoke_tests:input.frontend_smoke_tests,flutter_tests:input.flutter_tests,blocks_completed:input.blocks_completed,description:input.summary};return {latest:next,history:[...history,row],row};
}
export function backfillRelease(latest,history,{pr,approvedHead,mergeCommit}){
  if(!/^[0-9a-f]{40}$/.test(approvedHead)||!/^[0-9a-f]{40}$/.test(mergeCommit)||approvedHead===mergeCommit)fail('backfill exige SHAs completos e semanticamente distintos');
  if(latest.release?.approved_head||latest.release?.merge_commit)fail('release já recebeu backfill');
  latest.release={...latest.release,pr,approved_head:approvedHead,merge_commit:mergeCommit};const index=[...history].map((r,i)=>({r,i})).reverse().find(x=>x.r.version===latest.version&&x.r.approved_head==null&&x.r.merge_commit==null)?.i;if(index===undefined)fail('registro de autoria correspondente ausente no history');history[index]={...history[index],pr,approved_head:approvedHead,merge_commit:mergeCommit};return {latest,history};
}
function appendMd(row){writeFileSync(mdPath,`${readFileSync(mdPath,'utf8').replace(/\s*$/,'')}\n\n- ${row.snapshot_date} · ${row.version} · backend ${row.backend_tests} · frontend ${row.frontend_smoke_tests} · flutter ${row.flutter_tests} · blocks ${row.blocks_completed} · autoria: SHAs nulos.\n`);}
async function main(){const cmd=process.argv[2];let latest=read(latestPath),history=read(histPath);if(cmd==='author'){const input=read(arg('--input'));const out=authorRelease(latest,history,input);write(latestPath,out.latest);write(histPath,out.history);appendMd(out.row);}else if(cmd==='backfill'){const n=Number(arg('--from-pr'));const repo=gh(['repo','view','--json','nameWithOwner']).nameWithOwner;const pr=gh(['api',`repos/${repo}/pulls/${n}`]);if(!pr.merged)fail('PR não mergeado');const comments=gh(['api',`repos/${repo}/issues/${n}/comments?per_page=100`]);const parse=(m)=>{const c=[...comments].reverse().find(x=>String(x.body).includes(m));if(!c)fail(`${m} ausente`);return JSON.parse(String(c.body).split('\n').find(x=>x.startsWith('{')));};const att=parse('erp-porteiro-attestation:v1'),fin=parse('erp-post-merge-finalization:v1');if(fin.approvedHead!==att.head||fin.mergeCommit!==pr.merge_commit_sha)fail('atestado/fechamento/PR divergem');const out=backfillRelease(latest,history,{pr:n,approvedHead:att.head,mergeCommit:pr.merge_commit_sha});write(latestPath,out.latest);write(histPath,out.history);}else fail('comando: author|backfill');execFileSync('node',['scripts/kpi-freeze.mjs'],{cwd:ROOT,stdio:'inherit'});console.log(`kpi-release ${cmd}: OK`);}
if(process.argv[1]?.endsWith('kpi-release.mjs'))main().catch(e=>{console.error(`kpi-release: ${e.message}`);process.exitCode=1;});
